apiVersion: v1
kind: Service
metadata:
  name: inventario-service
  labels:
    app: inventario-app
spec:
  type: NodePort
  selector:
    app: inventario-app # Selecciona Pods estables y canary compartiendo app: inventario-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
