apiVersion: v1
kind: Service
metadata:
  name: inventario-service-canary
  labels:
    app: inventario-app
spec:
  type: NodePort
  selector:
    app: inventario-app # Distribución proporcional nativa: 4 pods Stable (80%) + 1 pod Canary (20%)
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30081
